analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
  errors:
    todo: info
linter:
  rules:
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sort_unnamed_constructors_first
    - use_rethrow_when_possible
    - always_require_non_null_named_parameters
    - directives_ordering
    - implementation_imports
    - sort_constructors_first
    - prefer_relative_imports
